export * from './logo';
export * from './arrowback';
export * from './phoneicon';
export * from './moreicon';
export * from './searchicon';
export * from './addicon';
export * from './qrcodeicon';
export * from './editicon';
export * from './righticon';